version: '3'

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/code
        ports:
            - 8000:8000
        command: python /code/manage.py runserver 0.0.0.0:8000
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/code
            - /code/node_modules
        ports:
          - 3000:3000
        expose:
            - 3000
        environment:
          - NODE_ENV=development
        depends_on:
          - backend
        command: npm start
