# Generated by Django 3.0.3 on 2020-02-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DownNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ackStatus', models.BooleanField(default=False, help_text='Status of Down nodes if Acknowledged')),
                ('downtime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('community_string', models.CharField(help_text='Community string used to snmpwalk', max_length=50)),
                ('vendor', models.CharField(help_text='Name of the vendor', max_length=50)),
                ('snmpIndex', models.CharField(help_text='Snmp index of the host', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('department', models.ForeignKey(help_text='select which department the reason is concerned with', on_delete=django.db.models.deletion.CASCADE, to='areacheck.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledged_node',
            fields=[
                ('node', models.OneToOneField(help_text='Id of Down Node', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='areacheck.DownNode')),
                ('acknowledged_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.CharField(help_text='Name of the Person The task is                                   Assigned To', max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Down'), (1, 'Up'), (2, 'Resolved')], default=0)),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_reason', models.TextField()),
                ('reason', models.ForeignKey(help_text='Sub Reason of the Reason', on_delete=django.db.models.deletion.PROTECT, to='areacheck.Reason')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(help_text='Name of the Interface', max_length=255)),
                ('description', models.CharField(help_text='Location or the description of the node', max_length=255)),
                ('snmp_index', models.CharField(help_text='Snmp index of the host', max_length=50, null=True)),
                ('online', models.IntegerField(help_text='Number of online ports')),
                ('monitor_status', models.BooleanField(default=True, help_text='Status of node')),
                ('last_update', models.DateField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areacheck.Host')),
            ],
        ),
        migrations.AddField(
            model_name='downnode',
            name='node',
            field=models.ForeignKey(help_text='ID of the down node', on_delete=django.db.models.deletion.PROTECT, to='areacheck.Node'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('downnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areacheck.Acknowledged_node')),
            ],
        ),
        migrations.AddField(
            model_name='acknowledged_node',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areacheck.SubReason'),
        ),
    ]
